# Site settings
title: Dive into Web
email: xue.wu0112@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal tech blogs.
baseurl: "/dive-into-web"

# Plugins
gems:
  - jekyll-coffeescript

# Markdown Processors: override default settings
kramdown:
  auto_ids: false

# Outputting: override default settings
permalink: none
excerpt_separator: <!--more-->

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: post
