# Site settings
title: Dive into WEB
email: xue.wu0112@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a place for my notes.
baseurl: "/dive-into-web"

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

# Plugins
gems:
  - jekyll-paginate
  - jekyll-coffeescript

# Markdown Processors
kramdown:
  auto_ids: false

# Outputting
permalink: none
paginate: 4
paginate_path: "/blogs/page/:num/"

defaults:
  - scope:
      type: posts
    values:
      layout: post
